---
# tasks file for docker_install
# Code modified from its original source:
# https://wwwin-github.cisco.com/raw/SVS-Automation/jenkins-worker/master/playbooks/roles/04-docker/tasks/main.yml
- name: Uninstall Podman and Prior Docker Installations
  become: true
  ansible.builtin.dnf:
    state: absent
    name: "{{ packages }}"
  vars:
    packages:
      "{{ package_removals }}"

- name: Set Fact for path to docker binary xz file
  ansible.builtin.set_fact:
    docker_arch_path: "{{ playbook_dir }}/roles/docker_install/files/docker-ce-{{ docker_version | default('24.0.6') }}-rpms.tar.xz"

- name: Unarchive the xz file
  ansible.builtin.unarchive:
    src: "{{ docker_arch_path }}"
    dest: /tmp/
    remote_src: no
    list_files: yes
  register: docker_rpms_unarchived

- name: Install Docker and Related RPM Packages
  become: true
  ansible.builtin.dnf:
    name: "{{ package_installs }}"
  register: docker_install

- name: Create docker group
  become: true
  ansible.builtin.group:
    local: true
    gid: 9000
    name: docker
    state: present

- name: "Create user {{ ansible_user }} on {{ inventory_hostname }} and add to docker group"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start and Enable the Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
    daemon_reload: yes
  when: docker_install is changed

- name: Remove rpm files and archive from tmp
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ docker_rpms_unarchived.files }}"
    - "{{ docker_arch_path }}"

- name: Confirm Docker Installed and Version
  ansible.builtin.shell: "docker --version"
