---
# vars file for docker_install
docker_version: 24.0.6
# Whether to retrieve from artifactory to push to target
# or push from the controller to the target when set local
docker_rpm_src: artifactory
artifact_path:  "https://engci-maven-master.cisco.com/artifactory/cmsp-sapphire-development-group/up-sac-utils/jenkins/v1/docker-ce-{{ docker_version | default('24.0.6') }}-rpms.tar.gz"
docker_rpm_filename: "docker-ce-{{ docker_version | default('24.0.6') }}-rpms.tar.gz"
# Which packages should be cleared out before installing docker
package_removals:
  - podman
  - containers-common
  - containerd
  - containerd.io
  - runc
  - docker
  - docker-engine
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate

# List the rpms to install. Should dervive from the unarchived tar.xz file
package_installs:
  - /tmp/containerd.io-1.6.24-3.1.el8.x86_64.rpm
  - /tmp/docker-ce-24.0.6-1.el8.x86_64.rpm
  - /tmp/docker-ce-cli-24.0.6-1.el8.x86_64.rpm
  - /tmp/docker-ce-rootless-extras-24.0.6-1.el8.x86_64.rpm
  - /tmp/docker-buildx-plugin-0.11.2-1.el8.x86_64.rpm
  - /tmp/docker-compose-plugin-2.21.0-1.el8.x86_64.rpm
