---
- name: Ensure swims_clients directory exists under $HOME
  file:
    path: '/home/jenkins/swims_clients'
    state: directory
    owner: 'jenkins'
    group: 'jenkins'
    mode: '0755'  
- name: Checkout swims clients signing binaries
  git:
    repo: 'https://wwwin-github.cisco.com/STO-Image-Signing/container_signing.git'
    dest: '/home/jenkins/swims_clients'
    version: 'master'

- name: Ensure verification_scripts directory exists under $HOME
  file:
    path: '/home/jenkins/verification_scripts'
    state: directory
    owner: 'jenkins'
    group: 'jenkins'
    mode: '0755'
- name: Checkout verification scripts
  git:
    repo: 'https://wwwin-github.cisco.com/STO-Image-Signing/signature-file-verification.git'
    dest: '/home/jenkins/verification_scripts'
    version: 'master'
- name: Install cosgin version 2.2.2 rpm
  yum:
    name: 'https://upsac.gen:cmVmdGtuOjAxOjE3MTAxODk3MzM6QTM3YzNhVllRTGxnUHlaaW5KNE9tU2RVU2I2@engci-maven.cisco.com/artifactory/up-sac-docker-local/binaries/cosign-2.2.2-1.x86_64.rpm'
    state: present