---
- name: Ensure swims_clients directory exists under $HOME
  file:
    path: '/home/jenkins/swims_clients'
    state: directory
    owner: 'jenkins'
    group: 'jenkins'
    mode: '0755'  
- name: Checkout swims clients signing binaries
  git:
    repo: 'https://wwwin-github.cisco.com/STO-Image-Signing/container_signing.git'
    dest: '/home/jenkins/swims_clients'
    version: 'master'

- name: Ensure verification_scripts directory exists under $HOME
  file:
    path: '/home/jenkins/verification_scripts'
    state: directory
    owner: 'jenkins'
    group: 'jenkins'
    mode: '0755'
- name: Checkout verification scripts
  git:
    repo: 'https://wwwin-github.cisco.com/STO-Image-Signing/signature-file-verification.git'
    dest: '/home/jenkins/verification_scripts'
    version: 'master'
- name: Install cosgin version 2.2.2 rpm
  yum:
    name:'https://engci-maven.cisco.com/artifactory/cmsp-sapphire-development-group/up-sac-utils/jenkins/v1/cosign-2.2.2-1.aarch64.rpm'
    state: present
